[package]
name = "advent_of_code_2023"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
pixels = "0.13.0"
winit = { version = "0.29.10", default-features = false, features = ["rwh_05", "x11", "wayland", "wayland-dlopen", "wayland-csd-adwaita"] }
